name:                RandomNumbers
version:             0.1.0.0


dependencies:
- random
- transformers

executables:
  RandomNumbers-exe:
    main:                Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base >= 4.7 && < 5