name:                http
version:             0.1.0.0
author:              "Author name here"

extra-source-files:
- README.md

executables:
  http:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -Wall
    - -fwarn-tabs
    dependencies:
    - base >= 4.7 && < 5
    - bytestring
    - text
    - wreq
