name:                mCheck
version:             0.1.0.0

# extra-source-files:
# - README.md
# - ChangeLog.md

dependencies:
- base >= 4.7 && < 5
- checkers
- QuickCheck

library:
  source-dirs: src

# executables:
#   mCheck-exe:
#     main:                Main.hs
#     source-dirs:         app
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - mCheck

tests:
  mCheck-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mCheck
    - QuickCheck
    - checkers
